services:
    netgen_ez_sylius.field_type.syliusproduct:
        class: Netgen\Bundle\EzSyliusBundle\Core\FieldType\SyliusProduct\Type
        parent: Ibexa\Core\FieldType\FieldType
        arguments:
            - "@sylius.repository.product"
        tags:
            - {name: ibexa.field_type, alias: syliusproduct}

    netgen_ez_sylius.field_type.syliusproduct.external_storage:
        class: Netgen\Bundle\EzSyliusBundle\Core\FieldType\SyliusProduct\SyliusProductStorage
        arguments:
            - "@sylius.repository.product"
            - "@sylius.factory.product"
            - "@sylius.manager.product"
            - "@ezpublish.locale.converter"
            - "@netgen_ez_sylius.field_type.syliusproduct.storage_gateway"
        tags:
            - {name: ibexa.field_type.externalStorageHandler, alias: syliusproduct}

    netgen_ez_sylius.field_type.syliusproduct.storage_gateway.doctrine:
        class: Netgen\Bundle\EzSyliusBundle\Core\FieldType\SyliusProduct\SyliusProductStorage\Gateway\DoctrineStorage
        arguments:
            - "@ezpublish.api.storage_engine.legacy.connection"

    netgen_ez_sylius.field_type.syliusproduct.storage_gateway:
        alias: netgen_ez_sylius.field_type.syliusproduct.storage_gateway.doctrine

#    netgen_ez_sylius.field_type.syliusproduct.converter:
#        class: Netgen\Bundle\EzSyliusBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\SyliusProductConverter
#        tags:
#            - {name: ibexa.field_type.storage.legacy.converter, alias: syliusproduct, lazy: true, callback: "::create"}

    netgen_ez_sylius.field_type.syliusproduct.indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        tags:
            - {name: ezpublish.field_type.indexable, alias: syliusproduct}
