parameters:
    netgen_ez_sylius.listeners.platform_ui_csrf_token.route_name: "ezpublish_rest_createSession"

services:
    netgen_ez_sylius.listeners.platform_ui_csrf_token:
        class: Netgen\Bundle\EzSyliusBundle\EventListener\PlatformUICsrfTokenListener
        arguments:
            - "%netgen_ez_sylius.listeners.platform_ui_csrf_token.route_name%"
            - "%ibexa.rest.csrf_token_intention%"
            - "@?security.csrf.token_manager"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.request_listener:
        class: Netgen\Bundle\EzSyliusBundle\EventListener\LegacyRequestListener
        arguments:
            - "@ibexa.config.resolver"
            - "@ibexa.api.repository"
            - "@security.token_storage"
            - "@netgen_ez_sylius.admin_user.provider.email_or_name_based"
        tags:
            - { name: kernel.event_subscriber }
