services:
    netgen_ez_sylius.shop_user.provider.email_or_name_based:
        class: Netgen\Bundle\EzSyliusBundle\Provider\EmailOrNameBased
        arguments:
            - "@sylius.shop_user_provider.email_or_name_based"
            - "@netgen_ez_sylius.repository.ez_sylius_user"
            - "@sylius.repository.shop_user"
            - "@ibexa.api.repository"
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'
            - "shop"

    netgen_ez_sylius.admin_user.provider.email_or_name_based:
        class: Netgen\Bundle\EzSyliusBundle\Provider\EmailOrNameBased
        arguments:
            - "@sylius.admin_user_provider.email_or_name_based"
            - "@netgen_ez_sylius.repository.ez_sylius_user"
            - "@sylius.repository.admin_user"
            - "@ibexa.api.repository"
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'
            - "admin"

    netgen_ez_sylius.user.provider.composite:
        class: Netgen\Bundle\EzSyliusBundle\Provider\Composite
        arguments:
            -
                - "@netgen_ez_sylius.admin_user.provider.email_or_name_based"
                - "@netgen_ez_sylius.shop_user.provider.email_or_name_based"
